### ISSUE TITLE
Tabs go away when creating a new branch

### ISSUE THREAD

**Issue by AaronM04** [anderoonies/git-tabs#24]
I ran `git checkout -b newbranch` and all the tabs went away. I'm running 0.3.0.

**Comment by anderoonies** [comment]
@AaronM04 sorry, i need to close out this repo and unpublish this from apm
the way workspaces are serialized has changed which no long makes this practical. there's been some activity in altering it—essentially making it so the buffer contents aren't wiped, but until then git-tabs isn't really feasible
thank you for using it, though!

**Comment by AaronM04** [comment]
Ah I see. Thanks for letting me know.

On May 25, 2016 5:02:28 PM PDT, Andy Bayer notifications@github.com wrote:

> @AaronM04 sorry, i need to close out this repo and unpublish this from
> apm
> the way workspaces are serialized has changed which no long makes this
> practical. there's been some activity in altering it—essentially making
> it so the buffer contents aren't wiped, but until then git-tabs isn't
> really feasible
> thank you for using it, though!
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/anderoonies/git-tabs/issues/24#issuecomment-221742832

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
